/*
 * ***************************************************************************
 *
 *         Copyright © 2016 unaussprechlich - ALL RIGHTS RESERVED
 *
 * ***************************************************************************
 */

package net.unaussprechlich.managedgui.lib.util;

import net.minecraft.client.Minecraft;
import net.minecraft.client.gui.FontRenderer;

/**
 * FontUtil Created by unaussprechlich on 20.12.2016.
 * Description:
 **/
public class FontUtil {


    private static FontUtil INSTANCE;

    public static FontUtil getINSTANCE() {
        if (INSTANCE == null)
            INSTANCE = new FontUtil();
        return INSTANCE;
    }

    private FontUtil() {
        //TODO: Autogenerated Singletone
    }


    public static FontRenderer getFrontRenderer(){
        return Minecraft.getMinecraft().fontRendererObj;
    }

    public static int widthOfString(String s){
        return getFrontRenderer().getStringWidth(s);
    }


    public static void draw(String text, int xStart, int yStart){
        getFrontRenderer().drawString(text, xStart, yStart, 0xffffff);
    }

    public static void drawWithShadow(String text, int xStart, int yStart){
        getFrontRenderer().drawStringWithShadow(text, xStart, yStart, 0xffffff);
    }

}
