package net.unaussprechlich.project.connect;

import com.palechip.hudpixelmod.extended.util.LoggerHelper;

/**
 * Connect Created by unaussprechlich on 20.12.2016.
 * Description:
 **/
public class Connect {

    private static Connect INSTANCE;

    public static Connect getINSTANCE() {
        if (INSTANCE == null)
            INSTANCE = new Connect();
        return INSTANCE;
    }

    private Connect() {
        //TODO: Autogenerated Singletone
    }

    public static void setup(){
        LoggerHelper.logInfo("Setting up Connect!");
        //ManagedGui.setup(new SetupHelper());
        //ManagedGui.setIsDisabled(false);
        //GuiManagerMG.addGUI("Connect", new ConnectGUI());

    }

}
