package net.unaussprechlich.project.connect.socket.io;

import com.mojang.realmsclient.gui.ChatFormatting;
import com.palechip.hudpixelmod.HudPixelMod;
import io.socket.client.IO;
import io.socket.client.Socket;
import net.minecraft.client.Minecraft;
import net.unaussprechlich.managedgui.lib.templates.defaults.container.DefNotificationContainer;
import net.unaussprechlich.managedgui.lib.util.RGBA;
import net.unaussprechlich.project.connect.gui.NotificationGUI;
import org.json.JSONException;
import org.json.JSONObject;

import java.net.URISyntaxException;
import java.util.Date;

/**
 * SocketConnection Created by Alexander on 23.02.2017.
 * Description:
 **/
public class SocketConnection {

    private static SocketConnection INSTANCE;

    private static Socket socket;
    private static final String SERVER_URL = "http://localhost:3000";


    public static SocketConnection getINSTANCE() {
        if (INSTANCE == null)
            INSTANCE = new SocketConnection();
        return INSTANCE;
    }

    private SocketConnection() {
        //TODO: Autogenerated Singletone
    }



    public void setup(){

        System.out.println("Setting up Socket.io");

        try {
            socket = IO.socket(SERVER_URL);

            socket.on(Socket.EVENT_CONNECT, args -> {
                try {

                    JSONObject obj = new JSONObject();
                    obj.append("username", Minecraft.getMinecraft().thePlayer.getName());
                    obj.append("uuid", Minecraft.getMinecraft().thePlayer.getGameProfile().getId());
                    obj.append("time", new Date().toString().replace(" ", ""));
                    obj.append("version", HudPixelMod.DEFAULT_VERSION.replace(" ", ""));

                    socket.emit("user_mc_log_in", obj);

                } catch (JSONException e) {
                    e.printStackTrace();
                }

            });

            socket.on(Socket.EVENT_DISCONNECT, args -> {});

            // Receiving an object
            socket.on("users_new_broadcast_message", args -> {
                JSONObject obj = (JSONObject)args[0];
                String message = null;
                try {
                    message = obj.getString("msg");
                    NotificationGUI.INSTANCE.addNotification(new DefNotificationContainer(message, "[Hud" + ChatFormatting.GOLD + "Pixel" +  ChatFormatting.WHITE + "]", RGBA.RED.get(), 20));
                } catch (JSONException e) {
                    e.printStackTrace();
                }
            });

            socket.connect();

        } catch (URISyntaxException e1) {
            e1.printStackTrace();
        }

    }
}
